<?php


namespace App\Repositories;

class LessonRepository extends EloquentRepository
{

    public function __construct()
    {
    }

    public function makeModel()
    {
        return parent::makeModel(); // TODO: Change the autogenerated stub
    }
}